export const CDN = "https://d2xsxph8kpxj0f.cloudfront.net/310519663360032476/eCRtfYiax3KEbRNYiyhxd5";

export const PROPERTIES = [
  {
    id: "iron-pointe",
    name: "Iron Pointe",
    badge: "NEW 2024",
    address: "39 Madison St, Newark, NJ",
    neighborhood: "North Ironbound",
    units: 80,
    stories: 4,
    yearBuilt: 2024,
    image: `${CDN}/iron_pointe_building_a43a0123.jpeg`,
    heroImage: `${CDN}/iron_pointe_hero_interior_8be65977.jpeg`,
    priceFrom: 2000,
    priceLabel: "$2,000/mo effective",
    highlight: "Featured — Newest Building",
    color: "#B8860B",
    description: "Newark's newest luxury address — 80 residences with rooftop NYC views, state-of-the-art gym, and 24-hour live security. Only pay electricity.",
    amenities: ["Rooftop Lounge", "Fitness Center 24/7", "24-Hr Live Security", "EV Charging", "Package Lockers", "Business Center", "Bike Storage", "High-Speed Wi-Fi"],
    features: ["In-Unit W/D", "Open Kitchen", "Walk-in Closets", "Floor-to-Ceiling Windows", "Quartz Countertops", "Stainless Appliances"],
    nearbyTransit: ["5 min to EWR Airport", "20 min to NYC Penn Station", "NJ Transit – Ironbound"],
    campaign: "/campaigns/commuters",
    slug: "/properties/iron-pointe",
  },
  {
    id: "university-pointe",
    name: "University Pointe",
    badge: "LEASING",
    address: "160 University Ave, Newark, NJ",
    neighborhood: "University Heights",
    units: 45,
    stories: 5,
    yearBuilt: 2022,
    image: `${CDN}/university_pointe_building_14056590.jpeg`,
    heroImage: `${CDN}/lobby_interior_6c231df5.png`,
    priceFrom: 1850,
    priceLabel: "$1,850/mo effective",
    highlight: "Steps from NJIT & Rutgers",
    color: "#2563EB",
    description: "Modern living near Newark's top universities. Ideal for young professionals and academics seeking a vibrant community close to campus.",
    amenities: ["Rooftop Terrace", "Study Lounge", "Fitness Center", "Controlled Access", "Package Lockers"],
    features: ["In-Unit W/D", "Modern Kitchen", "Hardwood Floors", "Large Windows", "Granite Countertops"],
    nearbyTransit: ["NJIT Campus – 2 min walk", "Rutgers Newark – 5 min", "Newark Penn Station – 10 min"],
    campaign: "/campaigns/genz",
    slug: "/properties/university-pointe",
  },
  {
    id: "river-pointe",
    name: "River Pointe",
    badge: "LEASING",
    address: "486 Market St, Newark, NJ",
    neighborhood: "Ironbound",
    units: 60,
    stories: 6,
    yearBuilt: 2021,
    image: `${CDN}/river_pointe_building_3eb6a035.jpeg`,
    heroImage: `${CDN}/rooftop_amenity_aed156a5.png`,
    priceFrom: 1950,
    priceLabel: "$1,950/mo effective",
    highlight: "Riverside Views",
    color: "#0891B2",
    description: "Sweeping Passaic River views from a vibrant Ironbound address. World-class Portuguese dining, parks, and culture right at your doorstep.",
    amenities: ["River View Rooftop", "Fitness Center", "Concierge", "Parking Available", "Pet Friendly"],
    features: ["In-Unit W/D", "River Views", "Open Floor Plans", "Modern Finishes", "Stainless Appliances"],
    nearbyTransit: ["Newark Penn Station – 8 min", "PATH to NYC – 25 min", "NJ Transit Bus"],
    campaign: "/campaigns/amenities",
    slug: "/properties/river-pointe",
  },
  {
    id: "502-market",
    name: "502 Market St.",
    badge: "LEASING",
    address: "502 Market St, Newark, NJ",
    neighborhood: "Ironbound",
    units: 32,
    stories: 4,
    yearBuilt: 2020,
    image: `${CDN}/market_502_building_full_6b1d1818.jpeg`,
    heroImage: `${CDN}/kitchen_interior_1ccf994f.png`,
    priceFrom: 1750,
    priceLabel: "$1,750/mo effective",
    highlight: "Boutique Building",
    color: "#7C3AED",
    description: "A boutique collection of thoughtfully designed residences in the heart of the Ironbound. Modern finishes meet authentic neighborhood character.",
    amenities: ["Rooftop Access", "Fitness Room", "Secure Entry", "Laundry Facilities", "Bike Storage"],
    features: ["Modern Kitchen", "Hardwood Floors", "High Ceilings", "Large Closets", "Natural Light"],
    nearbyTransit: ["Newark Penn Station – 10 min", "Ferry Street Dining – 2 min walk", "NJ Transit"],
    campaign: "/campaigns/modern-finishes",
    slug: "/properties/502-market",
  },
  {
    id: "556-market",
    name: "556 Market St.",
    badge: "LEASING",
    address: "556 Market St, Newark, NJ",
    neighborhood: "Ironbound",
    units: 28,
    stories: 4,
    yearBuilt: 2019,
    image: `${CDN}/market_556_building_full_8b94554c.jpeg`,
    heroImage: `${CDN}/lobby_interior_6c231df5.png`,
    priceFrom: 1700,
    priceLabel: "$1,700/mo effective",
    highlight: "Best Value in Ironbound",
    color: "#059669",
    description: "Exceptional value in Newark's most sought-after neighborhood. Spacious layouts, modern finishes, and the full Ironbound lifestyle experience.",
    amenities: ["Common Lounge", "Fitness Room", "Secure Entry", "Laundry", "Storage Units"],
    features: ["Renovated Interiors", "Modern Appliances", "Hardwood Floors", "Large Windows", "Storage"],
    nearbyTransit: ["Newark Penn Station – 12 min", "Ironbound Dining – walkable", "NJ Transit Bus"],
    campaign: "/campaigns/no-ny-tax",
    slug: "/properties/556-market",
  },
];

export const CAMPAIGNS = [
  {
    id: "commuters",
    slug: "/campaigns/commuters",
    title: "NYC Commuters",
    headline: "Live Better. Commute Less.",
    subheadline: "20 Minutes to Manhattan. 60% Less Rent.",
    description: "Why pay $4,500/mo in NYC when you can live in luxury for $2,000/mo effective — just 20 minutes from Midtown? Newark's Ironbound neighborhood offers the best of both worlds.",
    icon: "🚆",
    color: "oklch(0.55 0.18 250)",
    bgClass: "from-blue-950 to-blue-900",
    accentColor: "#3B82F6",
    keyPoints: [
      "20 min to NYC Penn Station via NJ Transit",
      "5 min to Newark Liberty International (EWR)",
      "Save $2,500+/mo vs comparable NYC apartments",
      "No NYC income tax — keep more of your paycheck",
      "Direct PATH train access to Lower Manhattan",
    ],
    properties: ["iron-pointe", "river-pointe"],
    cta: "Calculate Your NYC Savings",
    metaTitle: "NYC Commuter Apartments Newark NJ — 20 Min to Manhattan | Resipointe",
    metaDescription: "Live in luxury in Newark NJ, just 20 minutes from NYC. Save $2,500+/mo vs Manhattan apartments. No NYC income tax. Resipointe luxury apartments.",
  },
  {
    id: "no-ny-tax",
    slug: "/campaigns/no-ny-tax",
    title: "No NY Tax",
    headline: "Keep More of What You Earn.",
    subheadline: "New Jersey Residency = No NYC Income Tax",
    description: "NYC residents pay up to 3.876% city income tax on top of state taxes. By establishing New Jersey residency at Resipointe, you eliminate that entirely — saving thousands annually.",
    icon: "💰",
    color: "oklch(0.55 0.18 145)",
    bgClass: "from-emerald-950 to-emerald-900",
    accentColor: "#10B981",
    keyPoints: [
      "Eliminate NYC city income tax (up to 3.876%)",
      "On $120K salary: save ~$4,600/yr in city taxes alone",
      "NJ state income tax is lower than NYC combined rate",
      "Establish domicile in NJ — simple and legal",
      "Still commute to NYC for work — no career compromise",
    ],
    properties: ["556-market", "502-market"],
    cta: "Calculate Your Tax Savings",
    metaTitle: "Avoid NYC Income Tax — Live in Newark NJ | Resipointe",
    metaDescription: "Eliminate NYC city income tax by establishing New Jersey residency. Save thousands annually while living in luxury Newark apartments. Resipointe.",
  },
  {
    id: "aviators",
    slug: "/campaigns/aviators",
    title: "Flight Attendants & Pilots",
    headline: "5 Minutes to EWR. Home Between Flights.",
    subheadline: "Newark Liberty Airport — Your Backyard",
    description: "Built for aviation professionals. Iron Pointe sits just 5 minutes from Newark Liberty International Airport — the perfect base between trips. Crash-pad friendly, flexible leases available.",
    icon: "✈️",
    color: "oklch(0.55 0.18 200)",
    bgClass: "from-sky-950 to-sky-900",
    accentColor: "#0EA5E9",
    keyPoints: [
      "5 min drive to Newark Liberty International (EWR)",
      "United, Delta, American hub — all at EWR",
      "Flexible lease terms for aviation schedules",
      "Crash-pad friendly — short-term arrangements available",
      "24-hour security for peace of mind while traveling",
    ],
    properties: ["iron-pointe"],
    cta: "Book a Tour Around Your Schedule",
    metaTitle: "Apartments Near EWR Airport — Flight Attendants & Pilots | Resipointe",
    metaDescription: "5 minutes from Newark Liberty International Airport. Perfect for flight attendants and pilots. Flexible leases, luxury finishes, 24-hr security.",
  },
  {
    id: "genz",
    slug: "/campaigns/genz",
    title: "Gen Z Living",
    headline: "Your Vibe. Your Space. Your City.",
    subheadline: "Modern Living for the Next Generation",
    description: "Designed for how you actually live — open layouts for content creation, rooftop for the 'gram, co-working lounge for the side hustle, and a community that actually connects.",
    icon: "⚡",
    color: "oklch(0.55 0.18 300)",
    bgClass: "from-purple-950 to-purple-900",
    accentColor: "#A855F7",
    keyPoints: [
      "Rooftop with NYC skyline views (content gold)",
      "High-speed Wi-Fi building-wide",
      "Co-working lounge & business center",
      "Vibrant Ironbound food scene at your door",
      "Community events & resident networking",
    ],
    properties: ["university-pointe", "iron-pointe"],
    cta: "See the Vibe",
    metaTitle: "Gen Z Luxury Apartments Newark NJ — Modern Living | Resipointe",
    metaDescription: "Modern luxury apartments in Newark NJ designed for Gen Z. Rooftop views, co-working, high-speed Wi-Fi, vibrant community. Starting $1,850/mo.",
  },
  {
    id: "modern-finishes",
    slug: "/campaigns/modern-finishes",
    title: "Modern Finishes",
    headline: "Crafted for Those Who Notice the Details.",
    subheadline: "Luxury Interiors. Uncompromising Quality.",
    description: "Every surface, every fixture, every finish chosen with intention. Quartz countertops, wide-plank hardwood, floor-to-ceiling windows, and stainless steel appliances — because you deserve better.",
    icon: "✨",
    color: "oklch(0.58 0.12 65)",
    bgClass: "from-amber-950 to-stone-900",
    accentColor: "#D97706",
    keyPoints: [
      "Quartz countertops throughout",
      "Wide-plank hardwood flooring",
      "Floor-to-ceiling windows",
      "Stainless steel appliance packages",
      "Designer fixtures and hardware",
    ],
    properties: ["502-market", "iron-pointe"],
    cta: "View Interior Gallery",
    metaTitle: "Luxury Modern Finishes Apartments Newark NJ | Resipointe",
    metaDescription: "Quartz countertops, hardwood floors, floor-to-ceiling windows. Newark's most beautifully finished luxury apartments. Resipointe.",
  },
  {
    id: "amenities",
    slug: "/campaigns/amenities",
    title: "Amenities",
    headline: "Resort-Level Living. Newark Address.",
    subheadline: "Amenities That Elevate Every Day",
    description: "Rooftop lounge with NYC skyline views, state-of-the-art fitness center open 24/7, business center, EV charging, package lockers, and 24-hour live security. This is what luxury actually means.",
    icon: "🏙️",
    color: "oklch(0.55 0.18 30)",
    bgClass: "from-orange-950 to-red-900",
    accentColor: "#F97316",
    keyPoints: [
      "Rooftop lounge with NYC skyline panorama",
      "Fitness center open 24/7",
      "24-hour live security",
      "EV charging stations",
      "Business center & co-working lounge",
    ],
    properties: ["iron-pointe", "river-pointe"],
    cta: "Explore All Amenities",
    metaTitle: "Luxury Amenities Apartments Newark NJ — Rooftop & Gym | Resipointe",
    metaDescription: "Rooftop with NYC views, 24/7 gym, 24-hr live security, EV charging, business center. Newark's best amenity package. Resipointe luxury apartments.",
  },
];

export const FLOOR_PLANS = [
  { id: "fp-101", property: "iron-pointe", unit: "101", beds: 1, baths: 1, sqft: 725, price: 2750, effective: 2292, available: true, features: ["Backyard", "Ground Floor"] },
  { id: "fp-102", property: "iron-pointe", unit: "102", beds: 1, baths: 1, sqft: 670, price: 2750, effective: 2292, available: true, features: ["Backyard"] },
  { id: "fp-104", property: "iron-pointe", unit: "104", beds: 1, baths: 1, sqft: 705, price: 2400, effective: 2000, available: true, features: [] },
  { id: "fp-107", property: "iron-pointe", unit: "107", beds: 1, baths: 1, sqft: 705, price: 2400, effective: 2000, available: true, features: [] },
  { id: "fp-201", property: "iron-pointe", unit: "201", beds: 1, baths: 1, sqft: 725, price: 2500, effective: 2083, available: true, features: ["Corner Unit"] },
  { id: "fp-205", property: "iron-pointe", unit: "205", beds: 1, baths: 1, sqft: 538, price: 2400, effective: 2000, available: true, features: ["Compact"] },
  { id: "fp-213", property: "iron-pointe", unit: "213", beds: 1, baths: 1, sqft: 680, price: 2650, effective: 2208, available: true, features: ["Terrace"] },
  { id: "fp-214", property: "iron-pointe", unit: "214", beds: 1, baths: 1, sqft: 735, price: 2650, effective: 2208, available: true, features: ["Terrace"] },
  { id: "fp-108", property: "iron-pointe", unit: "108", beds: 2, baths: 2, sqft: 760, price: 3300, effective: 2750, available: true, features: ["Backyard"] },
  { id: "fp-207", property: "iron-pointe", unit: "207", beds: 2, baths: 2, sqft: 1047, price: 3300, effective: 2750, available: true, features: ["Corner Unit", "Large"] },
  { id: "fp-503", property: "iron-pointe", unit: "503", beds: 2, baths: 2, sqft: 1005, price: 3500, effective: 2917, available: true, features: ["Top Floor", "Views"] },
  { id: "fp-up-1a", property: "university-pointe", unit: "1A", beds: 1, baths: 1, sqft: 650, price: 2200, effective: 1833, available: true, features: [] },
  { id: "fp-up-2b", property: "university-pointe", unit: "2B", beds: 2, baths: 1, sqft: 900, price: 2800, effective: 2333, available: true, features: [] },
  { id: "fp-rp-3c", property: "river-pointe", unit: "3C", beds: 1, baths: 1, sqft: 700, price: 2350, effective: 1958, available: true, features: ["River View"] },
  { id: "fp-rp-4d", property: "river-pointe", unit: "4D", beds: 2, baths: 2, sqft: 1050, price: 3100, effective: 2583, available: true, features: ["River View", "Corner"] },
  { id: "fp-502-1a", property: "502-market", unit: "1A", beds: 1, baths: 1, sqft: 620, price: 2100, effective: 1750, available: true, features: [] },
  { id: "fp-556-1a", property: "556-market", unit: "1A", beds: 1, baths: 1, sqft: 600, price: 2050, effective: 1708, available: true, features: [] },
];

export const GALLERY_IMAGES = [
  { id: "g1", category: "exterior", property: "iron-pointe", url: `${CDN}/iron_pointe_building_a43a0123.jpeg`, caption: "Iron Pointe — 39 Madison St" },
  { id: "g2", category: "interior", property: "iron-pointe", url: `${CDN}/iron_pointe_hero_interior_8be65977.jpeg`, caption: "Iron Pointe — Living & Dining" },
  { id: "g3", category: "interior", property: "all", url: `${CDN}/kitchen_interior_1ccf994f.png`, caption: "Modern Kitchen — Quartz & Stainless" },
  { id: "g4", category: "amenities", property: "all", url: `${CDN}/lobby_interior_6c231df5.png`, caption: "Grand Lobby" },
  { id: "g5", category: "amenities", property: "iron-pointe", url: `${CDN}/rooftop_amenity_aed156a5.png`, caption: "Rooftop Terrace — NYC Views" },
  { id: "g6", category: "exterior", property: "university-pointe", url: `${CDN}/university_pointe_building_14056590.jpeg`, caption: "University Pointe — 160 University Ave" },
  { id: "g7", category: "exterior", property: "river-pointe", url: `${CDN}/river_pointe_building_3eb6a035.jpeg`, caption: "River Pointe — 486 Market St" },
  { id: "g8", category: "exterior", property: "502-market", url: `${CDN}/market_502_building_full_6b1d1818.jpeg`, caption: "502 Market St" },
  { id: "g9", category: "exterior", property: "556-market", url: `${CDN}/market_556_building_full_8b94554c.jpeg`, caption: "556 Market St" },
];

export const FEATURE_VOTE_OPTIONS = [
  { id: "coworking", label: "Co-working / Business Center", category: "amenities" },
  { id: "rooftop-pool", label: "Rooftop Pool", category: "amenities" },
  { id: "dog-park", label: "Dog Park / Pet Area", category: "amenities" },
  { id: "ev-charging", label: "EV Charging Stations", category: "amenities" },
  { id: "package-lockers", label: "Smart Package Lockers", category: "amenities" },
  { id: "concierge", label: "24/7 Concierge Service", category: "service" },
  { id: "grocery-delivery", label: "Grocery Delivery Locker", category: "service" },
  { id: "dry-cleaning", label: "Dry Cleaning Pickup", category: "service" },
  { id: "quartz-counters", label: "Quartz Countertops", category: "finishes" },
  { id: "hardwood-floors", label: "Wide-Plank Hardwood", category: "finishes" },
  { id: "smart-home", label: "Smart Home Controls", category: "tech" },
  { id: "fiber-internet", label: "Fiber Internet Included", category: "tech" },
  { id: "flexible-lease", label: "Flexible Lease Terms", category: "policy" },
  { id: "furnished-option", label: "Furnished Unit Option", category: "policy" },
];
